Repository itlabsio/k8s-itlabs-operator, pull requests merged in 2023-03, with the labels that each got.

#9 fix trigger sync to gitlab
  .github/workflows/gitlab-sync-on-merge-pr.yml
  .github/workflows/gitlab-sync-on-push.yml
Labels: fix

#11 remove servicemonitors
  .github/workflows/ci.yml
  README.md
  manifests/service.yaml
Labels: breaking

#12 Disable mutation if exception was raised
  k8s-itlabs-operator/operators/keycloak.py
  k8s-itlabs-operator/operators/postgresconnector.py
  k8s-itlabs-operator/operators/rabbitconnector.py
  k8s-itlabs-operator/operators/sentry.py
  k8s-itlabs-operator/operators/tests/keycloak_tests.py
  k8s-itlabs-operator/operators/tests/postgres_tests.py
  k8s-itlabs-operator/operators/tests/rabbit_tests.py
  k8s-itlabs-operator/operators/tests/sentry_tests.py
Labels: fix

#13 add liveness probe
  k8s-itlabs-operator/main.py
  k8s-itlabs-operator/operators/healthz.py
  k8s-itlabs-operator/operators/tests/heathz_tests.py
  manifests/deployment.yaml
  manifests/service.yaml
Labels: feature

#14 fix call operator only on creaing pods
  manifests/connectors/keycloak/webhook-config.yaml
  manifests/connectors/postgres/webhook-config.yaml
  manifests/connectors/rabbit/webhook-config.yaml
  manifests/connectors/sentry/webhook-config.yaml
Labels: fix

#15 Increased password length
  k8s-itlabs-operator/utils/passgen.py
Labels: feature
